doc ///
  Key
      "Canonical Series Tutorial"
  Headline
      Computing Nilsson series solutions to regular holonomic systems
  Description
    Text
      If $I$ is a regular holonomic D-module, the solutions of the system of differential equations
      I can be written as Nilsson series (Puiseux series with logarithms).
      The constructive version of this result is the canonical series method
      [@HREF("https://mathscinet.ams.org/mathscinet/pdf/1734566.pdf","SST, Sections 2.5, 2.6")@].
      In this tutorial, we illustrate an implementation of this method.

    Text
      If the input ideal $I$ is not regular, this method is not guaranteed to produce convergent
      series, or even @TO2 (holonomicRank, "holonomic rank")@ of $I$ formal power series solutions of $I$.
      There currently exists no computational method to verify whether I is a regular holonomic.
      In the case of GKZ systems, regularity has been characterized in terms of the input matrix.

    Text
      Currently, this contains the computation of @TO truncatedCanonicalSeries@, which computes the terms in
      canonical series up to a specified weight when they are logarithm free, as well as the leading
      terms via @TO cssLeadTerms@ for arbitrary regular holonomic I, which can include logarithms.

    Text
      This tutorial walks through the five-step algorithm for computing canonical Nilsson series solutions
      to regular holonomic $D$-modules using the {\tt HolonomicSystems} package. We will use a standard
      Gelfand-Kapranov-Zelevinsky (GKZ) hypergeometric system as our running example.

      First, load the package and define our Weyl algebra. We then construct the $D$-module ideal for
      the GKZ system associated to the matrix $A$ and parameter vector $\beta$.

    Example
      needsPackage "HolonomicSystems";
      A = matrix{{1, 1, 1}, {0, 1, 2}};
      beta = {1, 0};
      I = gkz(A, beta)

    Text
      Step 1: Gr\"obner deformation

      To compute series solutions, we must choose a generic weight vector $w \in \mathbb{Z}_{>0}^n$
      that determines the direction of the series expansion. The first step of the algorithm computes
      the initial ideal of $I$ with respect to the weight vector $(-w,w)$ using the @TO inw@ function
      from the @TO "WeylAlgebras::WeylAlgebras"@ package.
    Example
      w = {1, 0, 0};
      inI = inw(I, -w|w)

    Text
      Note: If the input vector $w$ is not sufficiently generic, meaning $(-w,w)$ does not lie in the
      interior of a cone in the Gr\"obner fan of $I$, an error will be thrown during this step.

      Step 2: Indicial ideal

      Next, we compute the indicial ideal of $I$. The indicial ideal is always torus-fixed, meaning it
      is generated by elements of the form $x^u \partial^v p(\theta_1, \dots, \theta_n)$, where
      $\theta_i = x_i\partial_i$. We can verify this property using @TO isTorusFixed@.

    Text
      The indicial ideal is formally the distraction of the initial ideal. We compute it using
      @TO indicialIdeal@, which returns an ideal in a commutative polynomial ring in the $\theta$
      variables.

    Example
      isTorusFixed(I)
      isTorusFixed(inI)
      indI = indicialIdeal(I, w)
      dinI = distraction(inI, ring indI);
      indI == dinI


    Text
      Step 3: Series' initial terms

      Because our original ideal $I$ is holonomic, its indicial ideal has height $n$ (its affine variety
      is zero-dimensional). The finite collection of points in this variety correspond to the exponents
      of $I$ with respect to $w$.

    Text
      To construct the actual leading terms of the series (which handles applying @TO solveFrobeniusIdeal@
      to the indicial ideal under the hood), we use @TO cssLeadTerms@. This outputs a list of elements
      in the Nilsson ring: a noncommutative algebra whose generators @TT "X_i"@, @TT "Xinv_i"@,
      @TT "logX_i"@ and @TT "dX_i"@ stand for the $i$-th variable of the Weyl algebra, its inverse,
      its logarithm and the corresponding partial derivative. See @TO truncatedCanonicalSeries@.

    Example
      netList cssLeadTerms(I, w)

    Text
      Step 4: Series support

      To construct more terms in the canonical series solutions, we need to know which monomials can appear
      with a nonzero coefficient. The function @TO nilssonSupport@ computes the supporting cone for the
      solutions. By passing an integer weight $k$ as a third argument, it returns a finite list of the
      truncated lattice points within that cone up to weight $k$.

    Example
      nilssonSupport(I, w, 3)

    Text
      Step 5: Canonical series expansions

      Finally, we compute the expanded series solutions. The function @TO truncatedCanonicalSeries@ takes
      the regular holonomic $D$-ideal $I$, the weight $w$, and a positive integer $k$. It outputs the
      generators it used together with the Nilsson series expansions for a basis of solutions to $I$,
      up to weight $k$.

      Because our parameter vector $\beta$ is nonresonant for this GKZ system, the roots naturally avoid
      integer shifts, guaranteeing a basis of standard logarithm-free series.

    Example
      (G, sols) = truncatedCanonicalSeries(I, w, 2);
      #sols
      sols#0

    Text
      {\bf A stop along the way: Exponents with multiplicity}

    Text
      To speed things up, if one wishes to avoid working with logarithms at all and only wants the
      exponents on the monomial parts of lead terms of canonical series solutions, the functions
      @TO cssExpts@ and @TO cssExptsMult@ return these values. The latter includes an integer
      indicating how many canonical series each exponent appears in, which can signal the presence
      of logarithms when the multiplicity is greater than 1.

      To compute only the exponents with respect to a weight vector, which are the exponents on the
      monomials in @TO cssLeadTerms@, use @TO cssExpts@ and @TO cssExptsMult@.

      Since I is holonomic, indicialIdeal(I,w) is height n in \CC[\theta], and the finite collection
      of points in \CC^n that make up its variety are the exponents of I.
      Thus, both @TT "cssExpts(I,w)"@ and @TT "cssExptsMult(I,w)"@ run primary decomposition routines
      on @TT "indicialIdeal(I,w)"@ and then solve for the corresponding closed points (and
      multiplicities, when asked).

      Consider a variation of our GKZ system with a different parameter vector:

    Example
      A = matrix{{1, 1, 1}, {0, 1, 2}};
      I = gkz(A, {10, 8});
      holonomicRank(I)
      cssExpts(I, {1, 0, 0})
      cssExptsMult(I, {1, 0, 0})

    Text
      In this case, the series corresponding to the exponent (2, 8, 0) is logarithm-free (actually,
      this is a hypergeometric polynomial), while the series corresponding to (0, 12, -2) has
      logarithms. [SST, page 138] has the polynomial, and four terms of the logarithmic series.

    Example
     R1 = QQ[z]
     W1 = makeWA R1
     a=1/2
     b=3
     c=5/3
     J = ideal(z*(1-z)*dz^2+(c-(a+b+1)*z)*dz-a*b) -- the Gauss hypergeometric equation, exponents 0, 1-c
     cssExpts(J,{1})
     inw(J,{-1,1})
     distraction(oo,QQ[s])
     factor oo_0
     c=1  -- Now we have a single exponent of multiplicity 2
     J = ideal(z*(1-z)*dz^2+(c-(a+b+1)*z)*dz-a*b)
     cssExpts(J,{1})
     cssExptsMult(J,{1})

    Example
      R2 = QQ[x_1..x_3]
      W2 = makeWA R2
      gens W2
      thetaRing = QQ[t_1,t_2,t_3] -- sets variable names t_i = x_i\dx_i
      f1= x_1*dx_1 -- this element already belongs to thetaRing
      distraction(f1,thetaRing)  -- checks out
      f2 = x_1^3*dx_1^3 -- this is a descending factorial in the theta variables
      distraction(f2,thetaRing)
      factor oo  -- now it looks like a descending factorial
      f = x_1^2*x_2^2*x_3*dx_1*dx_2^2*dx_3^2
      distraction(f,thetaRing)

    Text
      Here is an example that can be continued when more functions are implemented.
      This is worked out as [page 138, ex 3.5.3, SST].

    Example
      A = matrix{{1,1,1},{0,1,2}}
      I = gkz(A,{10,8})
      holonomicRank(I)
      cssExpts(I,{1,0,0})
      cssLeadTerms(I,{1,0,0})
      (G, sols) = truncatedCanonicalSeries(I,{1,0,0},2);
      netList sols

    Text
      Here is an example that can be continued when more functions are implemented.
      This is worked out as [page 136, ex 3.5.2, SST].

    Example
      A = matrix{{1,1,1,1,1},{-1,1,1,-1,0},{-1,-1,1,1,0}}
      I = gkz(A,{1,0,0})
      holonomicRank(I)
      w = {1,1,1,1,0} -- the weight must have one entry per variable of the Weyl algebra
      cssExpts(I,w)
      cssExptsMult(I,w)
      cssLeadTerms(I,w)

  Subnodes
    "Applications of canonical series"
    "cssExpts"
    "cssExptsMult"
    "cssLeadTerms"
    "distraction"
    "indicialIdeal"
    "isTorusFixed"
    "solveFrobeniusIdeal"
    "nilssonSupport"
    "truncatedCanonicalSeries"
///

///

doc ///
   Key
     distraction
     (distraction, Ideal, Ring)
     (distraction, RingElement, Ring)
   Headline
     the image in the thetaRing of a torus-fixed element or ideal in a Weyl algebra
   Usage
     distraction(I,thetaRing)
     distraction(f,thetaRing)
   Inputs
     I:Ideal
     f:RingElement
     thetaRing:PolynomialRing
       a stand in for the subring $k[\theta]$ generated by @TT "theta = x*dx"@
   Outputs
     :{Ideal,RingElement}
       that results from intersecting with the thetaRing of D, as in
       [@HREF("https://mathscinet.ams.org/mathscinet/pdf/1734566.pdf","SST")@, Lemma 2.3.1] to I.
   Description
    Text
      Given a monomial $x^u \partial^v$, this function rewrites it as a product $x^a p(\theta) \partial^b$,
      where $\theta_i = x_i \partial_i$ for $i = 1,\dots, n$. This is a step in a procedure for checking
      that D-ideal is torus-fixed, and is used in the @TO isTorusFixed@ routine.

      Given a torus fixed $D$-ideal, this function computes the distraction as in [SST, Corollary 2.3.5].
      This is necessary to compute indicial ideals [SST, Theorem 2.3.9, Corollary 2.3.5];
      the roots of the indicial ideals are the exponents of the starting terms of canonical series
      solutions of regular holonomic D-ideals.
    Example
      R1 = QQ[z]
      W1 = makeWA R1
      a=1/2
      b=3
      c=5/3
      J = ideal(z*(1-z)*dz^2+(c-(a+b+1)*z)*dz-a*b) -- the Gauss hypergeometric equation, exponents 0, 1-c
      cssExpts(J,{1})
      K = inw(J,{-1,1})
      distraction(K,QQ[s])
///

doc ///
   Key
     indicialIdeal
     (indicialIdeal, Ideal, List)
   Headline
     the image in the thetaRing of an indicial ideal in a Weyl algebra
   Usage
     indicialIdeal(I,w)
   Inputs
     I:Ideal
       in a WeylAlgebra that is torus-fixed
     w:List
       (generic) weights for $I$, of length half the number of variables in the Weyl algebra
   Outputs
     :Ideal
       that results from intersecting with the thetaRing of D with the result of extending
       the ideal in_(-w,w)(I) with the rational function
       field in the Weyl algebra variables, as in
       [@HREF("https://mathscinet.ams.org/mathscinet/pdf/1734566.pdf","SST")@, Theorem 2.3.9] to I.
   Description
    Text
      This computes the distraction of a torus fixed D-ideal [SST, Corollary 2.3.5].
      This is necessary to compute indicial ideals [SST, Theorem 2.3.9, Corollary 2.3.5];
      the roots of the indicial ideals are the exponents of the starting terms of canonical series
      solutions of regular holonomic D-ideals.
    Example
      R1 = QQ[z]
      W1 = makeWA R1
      a=1/2
      b=3
      c=5/3
      J = ideal(z*(1-z)*dz^2+(c-(a+b+1)*z)*dz-a*b) -- the Gauss hypergeometric equation, exponents 0, 1-c
      cssExpts(J,{1})
      K = inw(J,{-1,1})
      distraction(K,QQ[s])
      -- FIXME
      -- indicialIdeal(J,{-11}) -- returns the same answer as the previous distraction command
///

doc ///
   Key
     cssExpts
     (cssExpts, Ideal, List)
   Headline
     the exponents of the canonical series solutions of I in the direction of a weight vector
   Usage
     cssExpts(I,w)
   Inputs
     I:Ideal
       (regular) holonomic ideal in the Weyl algebra
     w:List
       (generic) weights for $I$, of length half the number of variables in the Weyl algebra
   Outputs
     :List
       of exponents of the exponents of the canonical series solutions of I
       in the direction of (-w,w), as in
       [@HREF("https://mathscinet.ams.org/mathscinet/pdf/1734566.pdf","SST")@, Theorem 2.3.11].
   Description
    Text
      There are examples in the tutorial that can be moved here.
      Code
      Pre
    Example
      R1 = QQ[z]
      W1 = makeWA R1
      a=1/2
      b=3
      c=5/3
      J = ideal(z*(1-z)*dz^2+(c-(a+b+1)*z)*dz-a*b) -- the Gauss hypergeometric equation, exponents 0, 1-c
      cssExpts(J,{1})
///

doc ///
   Key
     cssExptsMult
     (cssExptsMult, Ideal, List)
   Headline
     the exponents and multiplicities of the canonical series solutions
   Usage
     cssExptsMult(I,w)
   Inputs
     I:Ideal
       (regular) holonomic ideal in the Weyl algebra
     w:List
       (generic) weights for $I$, of length half the number of variables in the Weyl algebra
   Outputs
     :List
       of exponents of the starting exponents of the canonical series solutions of I
       in the direction of (-w,w), as in
       [@HREF("https://mathscinet.ams.org/mathscinet/pdf/1734566.pdf","SST")@, Theorem 2.3.11],
       together with their multiplicities.
   Description
    Text
      There are examples in the tutorial that can be moved here.
    Example
      R1 = QQ[z]
      W1 = makeWA R1
      a=1/2
      b=3
      c=5/3
      J = ideal(z*(1-z)*dz^2+(c-(a+b+1)*z)*dz-a*b) -- the Gauss hypergeometric equation, exponents 0, 1-c
      cssExpts(J,{1})
      c=1  -- Now we have a single exponent of multiplicity 2
      J = ideal(z*(1-z)*dz^2+(c-(a+b+1)*z)*dz-a*b)
      cssExpts(J,{1})
      cssExptsMult(J,{1})
///

doc ///
   Key
     isTorusFixed
     (isTorusFixed, Ideal)
   Headline
     checks if an ideal in a Weyl algebra is torus-fixed
   Usage
     isTorusFixed I
   Inputs
     I:Ideal
       in a WeylAlgebra
   Outputs
     :Boolean
       true if I is torus-fixed, false if not
   Description
    Text
       There is a natural action of the n-dimensional algebraic torus on $D$
       where $t \in (\mathbb{C}^*)^n$ acts on $\partial_i$ as $t_i\partial_i$ and on
       $x_i$ as $t_i^{-1}x_i$. The function isTorusFixed verifies whether a D-ideal is
       invariant under this action.

       See [@HREF("https://mathscinet.ams.org/mathscinet/pdf/1734566.pdf","SST")@],
       just before Lemma 2.3.1.
    Example
       W = makeWA(QQ[x_1,x_2])
       b = 2
       I = ideal(x_1*dx_1*(x_1*dx_1+b), x_1*dx_1*(x_2*dx_2+b),
	   x_2*dx_2*(x_1*dx_1+b), x_2*dx_2*(x_2*dx_2+b))
       isTorusFixed I
///

doc ///
   Key
     solveFrobeniusIdeal
     (solveFrobeniusIdeal, Ideal)
     (solveFrobeniusIdeal, Ideal, Ring)
   Headline
     solving Frobenius ideals
   Usage
     solveFrobeniusIdeal I
     solveFrobeniusIdeal(I, W)
   Inputs
     I:Ideal
       a Frobenius ideal which is m-primary
   Outputs
     :List
       containing monomials times logarithms of the variables
   Description
    Text
      See [@HREF("https://mathscinet.ams.org/mathscinet/pdf/1734566.pdf","SST")@, Algorithm 2.3.14].

      Here is [@HREF("https://mathscinet.ams.org/mathscinet/pdf/1734566.pdf","SST")@, Example 2.3.16]:
    Example
      R = QQ[t_1..t_5];
      I = ideal(t_1+t_2+t_3+t_4+t_5, t_1+t_2-t_4, t_2+t_3-t_4, t_1*t_3, t_2*t_4);
      solveFrobeniusIdeal I
    Example
      W = makeWeylAlgebra(QQ[x_1..x_5]);
      solveFrobeniusIdeal(I, W)
///


doc ///
   Key
     cssLeadTerms
    (cssLeadTerms, Ideal, List)
   Headline
     lead term of the canonical series solutions of I
   Usage
     cssLeadTerms(I, w)
   Inputs
     I:Ideal
       (regular) holonomic ideal in the Weyl algebra
     w:List
       (generic) weights for $I$, of length half the number of variables in the Weyl algebra
   Outputs
     :List
       containing monomials times logarithms in the variables
   Description
    Text
      This routine returns the lead terms of the canonical series solutions of $I$ with respect
      to the weight vector $w$.
      See [@HREF("https://mathscinet.ams.org/mathscinet/pdf/1734566.pdf","SST")@, Algorithm 2.3.14 and Lemma 2.5.10].

      Here is [@HREF("https://mathscinet.ams.org/mathscinet/pdf/1734566.pdf","SST")@, Example 2.3.16]:
    Example
      needsPackage "FourTiTwo"
      A = matrix{{1,1,1,1,1,1},{-2,0,0,0,0,1},{0,1,0,1,0,0},{1,1,2,0,0,1}}
      beta = {2,1,0,2}
      Hbeta = gkz(A,beta)
      w = {9,1,99999, 9999999, 3, 999}
      netList cssLeadTerms(Hbeta, w)
   Caveat
     Start terms whose exponents are integral are returned as elements of the Nilsson ring
     described in @TO truncatedCanonicalSeries@, but a start term with a rational exponent is
     returned as an @TO Expression@ instead, since the Nilsson ring only has integral powers of
     the variables. A list of start terms may therefore be inhomogeneous in this respect, and
     @TO truncatedCanonicalSeries@ does not accept the rational ones.
   SeeAlso
     cssExpts
     cssExptsMult
     truncatedCanonicalSeries
///

doc ///
   Key
     truncatedCanonicalSeries
    (truncatedCanonicalSeries, Ideal, List, ZZ)
   Headline
     canonical series solutions of a regular holonomic ideal, truncated by weight
   Usage
     (G, sols) = truncatedCanonicalSeries(I, w, k)
   Inputs
     I:Ideal
       a regular holonomic ideal in a Weyl algebra on $n$ variables
     w:List
       a (generic) weight vector of length $n$
     k:ZZ
       the truncation weight
   Outputs
     :Sequence
       a pair @TT "(G, sols)"@, where @TT "G"@ is the list of generators of $I$ that were used
       to set up the linear system, and @TT "sols"@ is a list of
       @TO2(holonomicRank, "holonomic rank")@ many canonical series, each truncated after
       $w$-weight $k$
   Description
    Text
      This carries out the canonical series method of
      [@HREF("https://mathscinet.ams.org/mathscinet/pdf/1734566.pdf","SST")@, Section 2.5]:
      the start terms of the series are computed with @TO cssLeadTerms@, the monomials that can
      occur are bounded by @TO nilssonSupport@, and the coefficients are found by solving one
      linear system per start term.
    Text
      Both the generators and the series are returned as elements of the {\em Nilsson ring} of
      the Weyl algebra, a noncommutative $\mathbb{Q}$-algebra with four blocks of generators
      @TT "dX_i"@, @TT "X_i"@, @TT "logX_i"@ and @TT "Xinv_i"@, standing for $\partial_{i+1}$,
      $x_{i+1}$, $\log x_{i+1}$ and $x_{i+1}^{-1}$ (note that the indexing starts at zero).
      Multiplication normal-orders the relations of the Weyl algebra together with
      $\partial_i \log x_i = \log x_i \, \partial_i + x_i^{-1}$, so that a product moves every
      $\partial$ to the right. Applying an operator to a function therefore means multiplying
      and then discarding the terms that still end in a $\partial$, since those annihilate
      constants.
    Text
      For instance, the Gauss hypergeometric equation with $c = 1$ has a single exponent of
      multiplicity two at the origin, so one of its two solutions carries a logarithm.
    Example
      W = makeWA(QQ[z]);
      J = ideal(z*(1-z)*dz^2 + (1-(1/2+3+1)*z)*dz - 3/2);
      (G, sols) = truncatedCanonicalSeries(J, {1}, 3);
      netList sols
    Text
      Truncation is by $w$-weight relative to the start term: each series satisfies the system
      up to terms whose weight exceeds that of its own start term by more than $k$.
    Text
      Applying the single generator to either series leaves nothing below relative weight $4$,
      one past the truncation, which is what it means for the truncation at $k = 3$ to be
      correct.
   Caveat
     The input is assumed to be regular holonomic. There is no algorithm to check this, and for
     an irregular ideal the output need not converge or even be a basis of formal solutions.

     Two limitations are inherited from the steps this builds on. Start terms with rational
     exponents are not supported, since the Nilsson ring only has integral powers of the
     variables; see the caveat in @TO cssLeadTerms@. And when @TO nilssonSupport@ returns a cone
     that is too small to contain the actual support of the series, the truncated linear system
     has no solution and an error is raised.
   SeeAlso
     cssLeadTerms
     nilssonSupport
     "Applications of canonical series"
///

doc ///
   Key
     nilssonSupport
    (nilssonSupport, Ideal, List)
    (nilssonSupport, Ideal, List, ZZ)
   Headline
     the cone supporting the exponents of the canonical series solutions
   Usage
     C = nilssonSupport(I, w)
     L = nilssonSupport(I, w, k)
   Inputs
     I:Ideal
       a regular holonomic ideal in a Weyl algebra on $n$ variables
     w:List
       a (generic) weight vector of length $n$
     k:ZZ
       a bound on the $w$-weight
   Outputs
     :{Cone,List}
       with two arguments, the cone in $\mathbb{R}^n$ containing the exponent vectors that can
       occur in a canonical series solution of $I$ relative to its start term; with three
       arguments, the list of lattice points of that cone of $w$-weight at most $k$
   Description
    Text
      Once the start terms are known, a canonical series solution has the form
      $x^\rho \sum_v c_v x^v (\log x)^\nu$, and the vectors $v$ that can occur with a nonzero
      coefficient lie in a rational cone determined by the initial forms of a Gr\"obner basis of
      $I$ with respect to $(-w,w)$; see
      [@HREF("https://mathscinet.ams.org/mathscinet/pdf/1734566.pdf","SST")@, Theorem 2.5.14].
      Truncating that cone at weight $k$ gives the finite set of monomials that
      @TO truncatedCanonicalSeries@ solves for.
    Example
      W = makeWeylAlgebra(QQ[x]);
      I = ideal(x*dx*(x*dx-3) - x*(x*dx+10)*(x*dx+20));
      nilssonSupport(I, {1})
      nilssonSupport(I, {1}, 4)
   Caveat
     The generators are assumed to have initial forms of $w$-weight zero. Passing an arbitrary
     ideal will generally give a different, and usually too small, cone. Internally
     @TO truncatedCanonicalSeries@ first replaces $I$ by generators normalized in this way, and
     the cone it uses may differ from @TT "nilssonSupport(I, w, k)"@ computed on the raw ideal.

     Truncating the cone at weight $k$ has to leave a bounded polyhedron. When the weight
     vector is zero on a ray of the cone this fails, and the error comes from
     @TO2("Polyhedra::latticePoints", "latticePoints")@ rather than from this function.
   SeeAlso
     truncatedCanonicalSeries
     cssLeadTerms
///

doc ///
   Key
     applyNilssonOperator
    (applyNilssonOperator, RingElement, RingElement)
   Headline
     apply an operator in the Nilsson ring to a Nilsson series
   Usage
     applyNilssonOperator(g, b)
   Inputs
     g:RingElement -- an operator in the Nilsson ring
     b:RingElement -- a Nilsson series
   Outputs
     :RingElement
       a table whose $(i,j)$ entry is the least $w$-weight, measured relative to the start term
       of @TT "sols#j"@, of a term surviving in @TT "G#i"@ applied to @TT "sols#j"@, or
       @TO infinity@ if the operator annihilates the series exactly
   Description
    Text
      In the Nilsson ring the product $g*b$ of an operator and a function is
      an operator whose normal form is a function plus terms ending in $\partial_i$
      which annihilate the constant function 1, so applying the operator $g$ to
      the function $b$ means keeping only the $\partial$-free part of the normal form.

      A series computed by @TT "truncatedCanonicalSeries(I, w, k)"@ is a solution of $I$
      up to weight $k$ precisely when apply every Nilsson operator gives a term with
      weight higher than $k$.
    Example
      W = makeWeylAlgebra(QQ[x_1,x_2,x_3]); w = {-1,0,1}
      netList(I = ideal(
	  x_1*dx_1^2 - x_3*dx_3^2 + dx_1 - dx_3,
	  x_2*dx_2^2 - x_3*dx_3^2 + dx_2 - dx_3,
	  x_1*dx_1 + x_2*dx_2 + x_3*dx_3 + 1))_*
      elapsedTime (G, sols) = truncatedCanonicalSeries(I, w, 2);
      netList G
      netList sols
      netList(residues = table(G, sols, applyNilssonOperator))
      assert all(flatten residues, f -> all(exponents f, e -> nilssonWeight(w, e) > 2))
    Text
      Here the first generator annihilates all four series exactly, while the other two leave a
      residual starting at relative weight three, one past the truncation.
   SeeAlso
     truncatedCanonicalSeries
///

end--
restart
path = prepend("~/Projects/M2/Workshops/Workshop-2019-Minneapolis/M2/Macaulay2/packages/", path)
installPackage "HolonomicSystems"
viewHelp solveFrobeniusIdeal

restart
debug needsPackage "HolonomicSystems"
needsPackage "FourTiTwo"

A = matrix{{1,1,1,1},{0,1,3,4}}
beta = {1,2}
Hbeta = gkz(A, beta)
W = ring Hbeta
w = {2,51,999,1}
I = inw(Hbeta, -w|w)

errorDepth=2
(G, sols) = truncatedCanonicalSeries(I, w, 4)

distraction(I_0, first createThetaRing W)
distraction(I, first createThetaRing W)
indicialIdeal(I, w)
cssExptsMult(Hbeta, w)

restart
debug needsPackage "HolonomicSystems"
needsPackage "FourTiTwo"

A = matrix{{1,1,1,1,1,1},{-2,0,0,0,0,1},{0,1,0,1,0,0},{1,1,2,0,0,1}}
beta = {2,1,0,2}
Hbeta = gkz(A,beta)
W = ring Hbeta
--w = {1,2,101,9999,51,7}
w = {9,1,99999, 9999999, 3, 999}
I = inw(Hbeta, -w|w)

solveFrobeniusIdeal(distraction(I, first createThetaRing W), W)
cssExptsMult(Hbeta, w)
holonomicRank Hbeta

restart
errorDepth=2
needsPackage "Dmodules"
needsPackage "FourTiTwo"

A = matrix{{1,1,1,1,1,1},{-2,0,0,0,0,1},{0,1,0,1,0,0},{1,1,2,0,0,1}}
beta = {2,1,0,2}
Hbeta = gkz(A,beta)
--w = {1,2,101,9999,51,7}
w = {9,1,99999, 9999999, 3, 999}

cssExptsMult(Hbeta, w)
cssLeadTerms(Hbeta, w)


A = matrix{{1,1,1,1},{0,1,3,4}}
beta = {1,2}
Hbeta = gkz(A,beta)
W = ring Hbeta
w = {2,51,999,1}
I = inw(Hbeta,-w|w)

(G, sols) = truncatedCanonicalSeries(I, w, 4)
