TEST get(currentFileDirectory | "basis.m2")
TEST get(currentFileDirectory | "basis2.m2")
TEST get(currentFileDirectory | "basis3.m2")
TEST get(currentFileDirectory | "basis4.m2")
TEST get(currentFileDirectory | "basis5.m2")
TEST get(currentFileDirectory | "basis6.m2")
