#ifndef _msolve_h_
#  define _msolve_h_

#  include "engine-includes.hpp"

#  if defined(__cplusplus)
class Computation;
class Matrix;
class RingElement;
#  else
typedef struct Computation Computation;
typedef struct Matrix Matrix;
typedef struct RingElement RingElement;
#  endif

/**
   Direct in-memory interface to msolve's F4 implementation (libneogb).

   Unlike the Msolve package's original route -- which serialized the input to
   a string, wrote it to a temporary file, ran the msolve executable, and then
   parsed its textual output back -- these routines hand msolve the flat
   (lengths, exponents, coefficients) arrays it uses internally and read the
   resulting basis back out of the same representation.  No files, no strings.
 */

#  if defined(__cplusplus)
extern "C" {
#  endif

/* Computes the reduced Groebner basis generated by the columns of M.  For a
   one-rowed matrix this is an ideal basis; for a multi-rowed matrix it is a
   module basis in Macaulay2's default term-over-position-up order, returned
   with the same target.
   M must be over a polynomial ring with a degree-reverse-lexicographic order
   and characteristic p with 0 < p < 2^31; msolve implements no other monomial
   order, and its finite field arithmetic is limited to word-size primes.  It
   is the caller's responsibility to check the monomial order.

   elim_block_len is the number of leading variables forming an elimination
   block (0 for none), matching msolve's `-e` option.  It must be zero for a
   module, since msolve does not combine elimination blocks with module
   orders.  nr_threads and info_level match its `-t` and `-v` options.

   Returns null, having set an error message, if the input is unsuitable. */
const Matrix* /* or null */ rawMsolveGB(const Matrix *M,
                                        int elim_block_len,
                                        int nr_threads,
                                        int info_level);

/* Computes the reduced Groebner basis of the submodule of R^r generated by the
   columns of M, where r is the number of rows of M, and returns it as a matrix
   with the same target.  This is the module counterpart of rawMsolveGB, which
   is the special case r = 1.

   The ring is subject to the same restrictions as above, except that no
   elimination block is allowed: msolve does not combine block orders with
   module orders.

   module_order selects the order on R^r refining the ring's own:
     0  position up over term, comparing components before monomials,
     1  term over position up, comparing monomials before components.
   In both, a larger row index gives the larger module monomial.

   The target's degrees are passed along so that msolve's degree by degree
   strategy sees the right degrees, but only when the ring's grevlex block is
   unweighted; with weights the degrees would have to be scaled to match the
   substitution described in msolve.cpp, and getting that wrong would only
   change the order pairs are selected in, never the answer.

   Returns null, having set an error message, if the input is unsuitable. */
const Matrix* /* or null */ rawMsolveModuleGB(const Matrix *M,
                                              int module_order,
                                              int nr_threads,
                                              int info_level);

/* Computes generators for the syzygy module of the columns of M.  The result
   has target source(M), so its columns are relations among the columns of M.
   msolve returns a Groebner basis of the syzygy module, which need not be a
   minimal generating set.  Zero columns are not currently supported.

   Returns null, having set an error message, if the input is unsuitable. */
const Matrix* /* or null */ rawMsolveSyzygy(const Matrix *M,
                                            int nr_threads,
                                            int info_level);

/* Computes a Groebner basis of the saturation of the ideal generated by the
   entries of M with respect to the product of the entries of F, using msolve's
   F4SAT, and returns it as a one-rowed matrix.  Both matrices must have one row
   and lie over the same ring, subject to the same restrictions as above; F4SAT
   additionally requires the characteristic to exceed 2^16.

   Returns null, having set an error message, if the input is unsuitable. */
const Matrix* /* or null */ rawMsolveSaturate(const Matrix *M,
                                              const Matrix *F,
                                              int nr_threads,
                                              int info_level);

/* Minimal graded Betti numbers of the cokernel of M, by rank extraction from
   msolve's nonminimal Schreyer resolution: the minimal complex is never built,
   only the ranks of the constant parts of the nonminimal differentials.  This
   is msolve's counterpart of rawMinimalBetti, and the result is packed the same
   way, so unpackEngineBetti reads it unchanged:

     [lo, hi, len, b(lo,0), ..., b(lo,len), ..., b(hi,0), ..., b(hi,len)]

   with the rows indexed by the slanted degree, so entry (i, j) is the number of
   generators of the minimal resolution at level j in degree i + j.

   length_limit truncates the table at that level; pass 0 for the whole
   resolution.  msolve computes one level beyond the limit regardless, since the
   Betti numbers at level i depend on the ranks at level i+1, so a truncated
   table is exact rather than an upper bound.

   The ring's grading is handed to msolve rather than inferred from its order,
   so a multigraded ring is resolved as readily as a singly graded one, and a
   ring whose grevlex weights have nothing to do with its degrees is too: msolve
   works in the heft degree reverse lexicographic order the grading induces, and
   minimal Betti numbers are an invariant of the module rather than of the order
   they were computed in.  What the grading must supply is a heft vector
   strictly positive on every variable, which is what Macaulay2 needs to speak
   of a resolution at all and what msolve's degree by degree schedule counts up
   in.

   The table is indexed by the multidegrees that occur, which under a singly
   graded ring is the ordinary table -- a degree is a vector of length one there
   and nothing else changes -- and under a multigraded one is the table
   Macaulay2 had no other way to obtain.  There is no separate heft indexed
   entry point: summing the records over a heft fibre gives that table back,
   which is a `applyKeys(B, (i,d,h) -> (i,{h},h), plus)` away in the interpreter.

   The result is packed for unpackMsolveBetti rather than for unpackEngineBetti,
   which reads the slanted layout the engine's own resolutions use and which
   only a degree that is a single number can be laid out in.  A multidegree
   minus a level is not a multidegree, and the entries are far too sparse for a
   dense layout in any case, so what is sent is the nonzero entries and nothing
   else, grouped by homological level:

     [r, len, n_0, ..., n_(len-1), (d_1, ..., d_r, heft, beta) x n_i per level i]

   where r is the degree length, len the homological length, n_i the number of
   entries at level i, beta the number of generators of the minimal resolution
   at that level in that multidegree, and heft its heft degree, the degree the
   slanted layout indexes the same entries by.  Levels past the last nonzero one
   are dropped, as they are from the slanted layout.

   Multidegrees are the ring's own, msolve's internal normalization having been
   undone, and within a level they come out in the degree group's own order,
   which is the order the buckets are sorted into rather than the order the
   resolution discovered them in.

   Returns null, having set an error message, if the input is unsuitable. */
M2_arrayint /* or null */ rawMsolveMinimalBetti(const Matrix *M,
                                                int length_limit,
                                                int nr_threads,
                                                int info_level);

/* The numerator of the Hilbert series of the cokernel of M over (1 - T)^n, as
   an element of the ring's degrees ring; this is what Macaulay2's poincare
   returns.

   It comes out of the same computation as rawMsolveMinimalBetti but costs far
   less: the numerator is the alternating sum of the ranks of *either* the
   minimal or the nonminimal resolution -- the rank corrections telescope away --
   so it is read straight off the Schreyer frame, which is pure combinatorics
   and performs no field arithmetic at all.  There is no length limit, since an
   alternating sum over a truncated resolution is missing its tail.

   The ring is under the same restrictions as above, and the numerator is a
   genuinely multigraded one when the ring is: it is read off the multidegree
   indexed table, so it lands in ZZ[T_0..T_(r-1)] with all r of the degrees
   ring's variables.  Note it is over prod_i (1 - T^(deg x_i)) rather than
   (1 - T)^n once the degrees are not all one, which is Macaulay2's convention
   too: poincare is the alternating sum of the graded Betti numbers whatever
   the grading, and the denominator never enters here.

   Returns null, having set an error message, if the input is unsuitable. */
const RingElement /* or null */ *rawMsolvePoincare(const Matrix *M,
                                                   int nr_threads,
                                                   int info_level);

/* A resolution computation object over msolve's nonminimal Schreyer resolution
   of the cokernel of M, to be driven with the usual rawResolutionGetFree and
   rawResolutionGetMatrix.

   Unlike everything else in this header, this one keeps msolve state alive
   between calls, which is what lets the two halves of the work be paid for
   separately.  Building the object runs the module Groebner basis and the
   whole Schreyer frame; the frame is combinatorial, so every free module in
   the resolution -- its rank and the degrees of its generators -- is known
   from that point on with no field arithmetic having been done past the
   Groebner basis.  rawResolutionGetMatrix is what triggers a differential to
   be computed, and only up to the level asked for: the block at level i in
   degree d reduces against level i-1 in degrees at most d, so D_i requires
   D_2 ... D_{i-1} and nothing above.  Levels already computed are remembered,
   so asking again is free, and asking out of order costs no more than asking
   in order.

   The complex is the *nonminimal* one, as with Macaulay2's own
   res(..., Strategy => Nonminimal): F_1 is the Groebner basis of the image of
   M, not the columns of M -- msolve keeps no change of basis from one to the
   other -- and the ranks are the frame ranks rather than the minimal Betti
   numbers.  rawResolutionBetti reports those frame ranks for types 0 and 1;
   for minimal Betti numbers use rawMsolveMinimalBetti, which extracts them
   from ranks alone and never materializes a differential.

   length_limit truncates the frame at that level; pass 0 for the whole
   resolution.  Note there is no level that is always enough -- the frame is
   nonminimal, so Hilbert's syzygy theorem does not bound it, and it really can
   run past the number of variables.

   Unlike the one shot entry points above, this one still infers the grading
   from the order, so the ring must be singly graded with each variable's degree
   equal to its weight in the grevlex block.  The difference is that the free
   modules here are Macaulay2 objects handed back one at a time rather than an
   array of degrees, and building them over a general degree monoid is work
   msolve is already ready for -- it reports multidegrees -- but this side is
   not.

   Returns null, having set an error message, if the input is unsuitable. */
Computation /* or null */ *rawMsolveResolution(const Matrix *M,
                                               int length_limit,
                                               int nr_threads,
                                               int info_level);

/* True if this M2 was built against libmsolve, so the routines above work. */
M2_bool rawMsolvePresent();

#  if defined(__cplusplus)
}
#  endif

#endif

// Local Variables:
// indent-tabs-mode: nil
// End:
