#ifndef _msolve_h_
#  define _msolve_h_

#  include "engine-includes.hpp"

#  if defined(__cplusplus)
class Matrix;
#  else
typedef struct Matrix Matrix;
#  endif

/**
   Direct in-memory interface to msolve's F4 implementation (libneogb).

   Unlike the Msolve package's original route -- which serialized the input to
   a string, wrote it to a temporary file, ran the msolve executable, and then
   parsed its textual output back -- these routines hand msolve the flat
   (lengths, exponents, coefficients) arrays it uses internally and read the
   resulting basis back out of the same representation.  No files, no strings.
 */

#  if defined(__cplusplus)
extern "C" {
#  endif

/* Computes the reduced Groebner basis of the ideal generated by the entries of
   the one-rowed matrix M, and returns it as a one-rowed matrix over the same
   ring.  M must be over a polynomial ring with a degree-reverse-lexicographic
   order and characteristic p with 0 < p < 2^31; msolve implements no other
   monomial order, and its finite field arithmetic is limited to word-size
   primes.  It is the caller's responsibility to check the monomial order.

   elim_block_len is the number of leading variables forming an elimination
   block (0 for none), matching msolve's `-e` option.  nr_threads and
   info_level match its `-t` and `-v` options.

   Returns null, having set an error message, if the input is unsuitable. */
const Matrix* /* or null */ rawMsolveGB(const Matrix *M,
                                        int elim_block_len,
                                        int nr_threads,
                                        int info_level);

/* Computes a Groebner basis of the saturation of the ideal generated by the
   entries of M with respect to the product of the entries of F, using msolve's
   F4SAT, and returns it as a one-rowed matrix.  Both matrices must have one row
   and lie over the same ring, subject to the same restrictions as above; F4SAT
   additionally requires the characteristic to exceed 2^16.

   Returns null, having set an error message, if the input is unsuitable. */
const Matrix* /* or null */ rawMsolveSaturate(const Matrix *M,
                                              const Matrix *F,
                                              int nr_threads,
                                              int info_level);

/* True if this M2 was built against libmsolve, so the routines above work. */
M2_bool rawMsolvePresent();

#  if defined(__cplusplus)
}
#  endif

#endif

// Local Variables:
// indent-tabs-mode: nil
// End:
